import {
  pgTable,
  text,
  integer,
  boolean,
  timestamp,
  uuid,
  date,
} from "drizzle-orm/pg-core";

/**
 * ─────────────────────────────────────────────────────────────
 * Design notes
 * ─────────────────────────────────────────────────────────────
 * - `webinars` holds everything that changes per campaign: hero copy,
 *   schedule, pricing, video, seats/scarcity display, registration link.
 * - Testimonials / bonuses / FAQs / feature highlights / audience segments
 *   are a SHARED content pool (edited once, shown on whichever webinar is
 *   active). This avoids re-entering the same proof/social content every
 *   time a new campaign is created. If you'd rather scope any of these
 *   per-webinar later, it's a one-column migration (add webinarId FK) —
 *   flag it and we'll change it.
 * - Rich headline text (e.g. "In {gold}3 Simple Steps{/gold} Master...")
 *   uses inline {gold}...{/gold} / {red}...{/red} tags, parsed by
 *   <Highlight> on the client. Keeps admin editing to a plain text input
 *   without needing a full rich-text editor.
 * - Money is stored as integer paise (e.g. ₹99 => 9900), per convention.
 * - Auth tables (user/session/account/verification) are generated by the
 *   better-auth Drizzle adapter — see src/lib/auth.ts.
 */

export const webinars = pgTable("webinars", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  isActive: boolean("is_active").notNull().default(false),

  // Top urgency bar
  announcementBarText: text("announcement_bar_text").notNull().default(
    "Register Now, Seats are Filling Fast only for First 100 People"
  ),
  countdownTargetAt: timestamp("countdown_target_at", { withTimezone: true }),

  // Hero
  heroHeadline: text("hero_headline").notNull(),
  heroSubheadline: text("hero_subheadline"),
  heroVideoUrl: text("hero_video_url"),
  heroVideoThumbnailUrl: text("hero_video_thumbnail_url"),

  // Schedule / logistics chips
  eventDate: date("event_date").notNull(),
  eventTime: text("event_time").notNull(), // e.g. "7 PM"
  language: text("language").notNull().default("Hindi and English"),
  mode: text("mode").notNull().default("Zoom"),

  // Social proof strip
  ratingValue: text("rating_value").notNull().default("4.9"),
  ratingLabel: text("rating_label").notNull().default("Rating"),
  studentsTrainedLabel: text("students_trained_label")
    .notNull()
    .default("10,000+ Students Trained"),
  seatsRegisteredLabel: text("seats_registered_label").default(
    "2,847 already registered"
  ),

  // Pricing & scarcity
  originalPricePaise: integer("original_price_paise").notNull().default(479400),
  offerPricePaise: integer("offer_price_paise").notNull().default(9900),
  seatsLeftCount: integer("seats_left_count"),
  seatsLeftText: text("seats_left_text").default("Filling Fast Only 2 Seats Left"),

  // CTA
  registrationUrl: text("registration_url").notNull(),

  // Mentor (denormalized on the webinar so different campaigns can feature
  // different mentors later; today it's one person)
  mentorName: text("mentor_name").notNull().default("Nishant Chopra"),
  mentorTagline: text("mentor_tagline").notNull().default(
    "8+ Years of Teaching Experience"
  ),
  mentorBio: text("mentor_bio"),
  mentorPhotoUrl: text("mentor_photo_url"),
  mentorBadges: text("mentor_badges"), // comma-separated short badges

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** "STUDENT REVIEW" screenshot-style cards (image-only proof) */
export const testimonialScreenshots = pgTable("testimonial_screenshots", {
  id: uuid("id").primaryKey().defaultRandom(),
  imageUrl: text("image_url").notNull(),
  altText: text("alt_text").notNull().default("Student review screenshot"),
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** "Hear From Our Students" styled quote cards */
export const testimonials = pgTable("testimonials", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  location: text("location"),
  quote: text("quote").notNull(),
  rating: integer("rating").notNull().default(5),
  avatarUrl: text("avatar_url"),
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** "Special Webinar Bonuses" stack */
export const bonuses = pgTable("bonuses", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  valuePaise: integer("value_paise").notNull(),
  description: text("description"),
  iconName: text("icon_name").notNull().default("Gift"), // lucide-react icon key
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** "Why This Workshop Is a Game-Changer" grid */
export const featureHighlights = pgTable("feature_highlights", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  iconName: text("icon_name").notNull().default("Sparkles"),
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
});

/** "Who This Is Perfect For" grid */
export const audienceSegments = pgTable("audience_segments", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  iconName: text("icon_name").notNull().default("Mic"),
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
});

/** FAQ accordion */
export const faqs = pgTable("faqs", {
  id: uuid("id").primaryKey().defaultRandom(),
  question: text("question").notNull(),
  answer: text("answer").notNull(),
  order: integer("order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
});

// better-auth tables (user/session/account/verification) — generated by
// `npx @better-auth/cli generate`, do not hand-edit; re-run the CLI if you
// change auth config (plugins, additional fields, etc).
export * from "./auth-schema";

/** Singleton row for site-wide fallback settings */
export const siteSettings = pgTable("site_settings", {
  id: integer("id").primaryKey().default(1),
  siteName: text("site_name").notNull().default("Nishant Chopra Live"),
  defaultRegistrationUrl: text("default_registration_url"),
  supportEmail: text("support_email"),
  supportPhone: text("support_phone"),
  footerText: text("footer_text"),
});
